version: '3'

services:
  apache:
      image: httpd:2.4
      volumes:
        - ./:/var/www
        - ./_docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      depends_on:
        - php
  nginx:
      image: nginx:1.13
      ports:
        - 80:80
      volumes:
        - ./:/var/www
        - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - apache
  php:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./:/var/www
      # - ./_docker/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user 
      MYSQL_PASSWORD: test_pass
    volumes:
      - ./databases/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 85:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootroot