version: '3'

services:
  app:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    ports:
    - 8080:80
    volumes:
      - ./:/var/www
      - ./_docker/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    container_name: project_app

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user 
      MYSQL_PASSWORD: test_pass
    volumes:
      - ./databases/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 85:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootroot